#!/bin/sh

# Colors
NC='\033[0m'
BRed='\033[1;33m'

echo "\n1. Install Laravel Sail\n"
composer require laravel/sail --dev

echo "\n${BRed}Do you want to use MySQL or MariaDB on this project? (1 for MySQL or 2 for MariaDB)${NC}"
read DATABASE

if [ "$DATABASE" == "1" ]; then
    echo "\n2. Create docker-compose.yml file with MySQL and Redis\n"
    php artisan sail:install --with=mysql,redis -q -n
else
    echo "\n2. Create docker-compose.yml file with MariaDB and Redis\n"
    php artisan sail:install --with=mariadb,redis -q -n
fi
