#!/bin/sh

echo "\n${BBlue}Installing .git/hooks${NC}"
source <(curl -s https://raw.githubusercontent.com/iammayron/devsquad-setup/master/hooks/run)

echo "\n${BBlue}Installing necessary PHP packages${NC}"
source <(curl -s https://raw.githubusercontent.com/iammayron/devsquad-setup/master/vendor-packages)

echo "\n${BBlue}Installing verification tools' settings files${NC}"
source <(curl -s https://raw.githubusercontent.com/iammayron/devsquad-setup/master/verification-tools/run)

echo "\n${BBlue}Installing necessary GitHub Actions${NC}"
source <(curl -s https://raw.githubusercontent.com/iammayron/devsquad-setup/master/actions/run)

echo "\n${BBlue}Installing workspace directory${NC}"
if [ ! -d './workspace' ]; then
    mkdir ./workspace;
    echo "*
!.gitignore" > ./workspace/.gitignore
fi

echo "\n${BBlue}All done! 😎${NC}"
