#!/bin/sh

# Colors
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;33m'
CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`

echo "\n${BBlue}Installing .git/hooks${NC}"
sh -c "$(curl -fsSl https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/${CURRENT_BRANCH}/hooks/run)"

echo "\n${BBlue}Installing necessary PHP packages${NC}"
sh -c "$(curl -fsSl https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/${CURRENT_BRANCH}/vendor-packages)"

echo "\n${BBlue}Installing verification tools' settings files${NC}"
sh -c "$(curl -fsSl https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/${CURRENT_BRANCH}/verification-tools/run)"

echo "\n${BBlue}Installing necessary GitHub Actions${NC}"
sh -c "$(curl -fsSl https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/${CURRENT_BRANCH}/actions/run)"

# Laravel Sail
sh -c "$(curl -fsSl https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/${CURRENT_BRANCH}/laravel-sail)"

echo "\n${BBlue}Installing workspace directory${NC}"
if [ ! -d './workspace' ]
then
    mkdir ./workspace
    echo "*
!.gitignore" > ./workspace/.gitignore
fi

echo "\n${BBlue}All done! 😎${NC}"
