#!/bin/sh
phpVersions=$(grep -o '"php": "[^"]*' composer.json | grep -o '[^"]*$' | sed 's/\^*\.*//g')
IFS='|' read -ra PHPVERSION <<<"$phpVersions"
max=${PHPVERSION[0]}
for i in "${PHPVERSION[@]}"; do
    if [ "$((i > max))" -ne 0 ]; then
        max=$i
    fi
done
phpVersion=$(echo $max | cut -c 1)

laravelVersion=$(composer show 'laravel/framework' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1)

echo "\n1. Update composer.lock file\n"
composer update

echo "\n2. Install PHP Unit\n"
if [ "$phpVersion" -le 7 ]; then
    composer require phpunit/phpunit "^8.5.8|^9.3.3" --dev
else
    composer require phpunit/phpunit "^9.3.3" --dev
fi

echo "\n3. Install PHP Mess Detector\n"
composer require phpmd/phpmd "^2.9" --dev

echo "\n4. Install PHP Code Sniffer\n"
composer require squizlabs/php_codesniffer "^3.6" --dev

echo "\n5. Install PHP CS Fixer\n"
if [ "$phpVersion" -le 7 ]; then
    composer require friendsofphp/php-cs-fixer "^2.0" --dev
else
    composer require friendsofphp/php-cs-fixer "^3.0" --dev
fi

if [ "$laravelVersion" == v8* ]; then
    echo "\n6. Install Larastan\n"
    composer require --dev nunomaduro/larastan

    echo "\n7. Install Paratest\n"
else
    echo "\n6. Install Paratest\n"
fi

composer require brianium/paratest "^6.2" --dev
