#!/bin/sh
laravelVersion=$(composer show 'laravel/framework' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1)

echo "1. Install .php-cs-fixer.php"
curl -s -o .php-cs-fixer.php "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/verification-tools/.php-cs-fixer.php"

echo "2. Install phpcs.xml"
curl -s -o phpcs.xml "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/verification-tools/phpcs.xml"

echo "3. Install phpmd.xml"
curl -s -o phpmd.xml "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/verification-tools/phpmd.xml"

echo "4. Install phpunit.xml"
curl -s -o phpunit.xml "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/verification-tools/phpunit.xml"

echo "5. Install phpunit-ci.xml"
curl -s -o phpunit-ci.xml "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/verification-tools/phpunit-ci.xml"

echo "6. Install .env.ci"
curl -s -o .env.ci "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/verification-tools/.env.ci"

if [ "$laravelVersion" == v8* ]; then
    echo "7. Install phpstan.neon"
    curl -s -o phpstan.neon "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/verification-tools/phpstan.neon"
fi
