#!/bin/bash
# The script below adds the branch name automatically to
# every one of your commit messages. The regular expression
# below searches for JIRA issue key's. The issue key will
# be extracted out of your branch name

REGEX_ISSUE_ID="[a-zA-Z0-9,\.\_\-]+-[0-9]+"

NC='\033[0m'
BRed='\033[1;31m'

# Find current branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Extract issue id from branch name
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

# Extract commit message
COMMIT_MESSAGE=$(cat "$1")

# Exit and continue when the branch name doesn't have a JIRA issue key
if [ -z $ISSUE_ID ]; then
    echo -e "⚠️  ${BRed}The Branch doesn't have Jira task code on it... ${NC} \n"

    exit 0
fi

echo "$ISSUE_ID: $COMMIT_MESSAGE" > $1
