#!/bin/sh

NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

laravelVersion=$(composer show 'laravel/framework' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1)
sailPreference=$(cat .env | grep SAIL_PRE_PUSH_PREFERENCE | cut -d '=' -f2 | tr '[:upper:]' '[:lower:]')

NAME=$(git branch | grep '*' | sed 's/* //')
echo "Running pre-push hook on: ${BBlue}" $NAME "${NC}"

# ----------------------------------------------------------------------------------------
# 1. PHP Mess Detector
echo "${BBlue}1. PHP Mess Detector${NC}"
if [ "$sailPreference" = true ]; then
  ./vendor/bin/sail php ./vendor/bin/phpmd app text ./phpmd.xml
else
  ./vendor/bin/phpmd app text ./phpmd.xml
fi

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}1.... php mess detector${NC}"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 2. PHP Code Sniffer
echo "${BBlue}2. PHP Code Sniffer${NC}"
if [ "$sailPreference" = true ]; then
  ./vendor/bin/sail php ./vendor/bin/phpcs --standard=phpcs.xml
else
  ./vendor/bin/phpcs --standard=phpcs.xml
fi

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}2.... php code sniffer${NC}"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 3. Laravel Pint
echo "${BBlue}3. Laravel Pint${NC}"
if [ "$sailPreference" = true ]; then
  ./vendor/bin/sail php ./vendor/bin/pint --test
else
  ./vendor/bin/pint --test
fi

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}3.... laravel pint${NC}"
    exit 1
fi

if [ "$laravelVersion" == v8* ]; then
    # ----------------------------------------------------------------------------------------
    # 4. Larastan
    echo "${BBlue}4. Larastan${NC}"
    if [ "$sailPreference" = true ]; then
        ./vendor/bin/sail php ./vendor/bin/phpstan analyse
    else
        ./vendor/bin/phpstan analyse
    fi

    STATUS_CODE=$?
    if [ $STATUS_CODE -ne 0 ]; then
        echo "${BRed}4.... larastan${NC}"
        exit 1
    fi

    # ----------------------------------------------------------------------------------------
    # 5. PHP Unit Tests
    echo "${BBlue}5. Running Tests${NC}"
    if [ "$sailPreference" = true ]; then
        ./vendor/bin/sail php artisan test --parallel
    else
        php artisan test --parallel
    fi

    STATUS_CODE=$?
    if [ $STATUS_CODE -ne 0 ]; then
        echo "${BRed}5.... phpunit tests${NC}"
        exit 1
    fi
else
    # ----------------------------------------------------------------------------------------
    # 4. PHP Unit Tests
    echo "${BBlue}4. Running Tests${NC}"
    if [ "$sailPreference" = true ]; then
        ./vendor/bin/sail php artisan test --parallel
    else
        php artisan test --parallel
    fi

    STATUS_CODE=$?
    if [ $STATUS_CODE -ne 0 ]; then
        echo "${BRed}4.... phpunit tests${NC}"
        exit 1
    fi
fi
