#!/bin/sh

NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

laravelVersion=$(composer show 'laravel/framework' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1)

NAME=$(git branch | grep '*' | sed 's/* //')
echo "Running pre-push hook on: ${BBlue}" $NAME "${NC}"

# ----------------------------------------------------------------------------------------
# 1. PHP Mess Detector
echo "${BBlue}1. PHP Mess Detector${NC}"
./vendor/bin/phpmd app text ./phpmd.xml

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}1.... php mess detector${NC}"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 2. PHP Code Sniffer
echo "${BBlue}2. PHP Code Sniffer${NC}"
./vendor/bin/phpcs --standard=phpcs.xml

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}2.... php code sniffer${NC}"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 3. PHP Code Fixer
echo "${BBlue}3. PHP Code Fixer${NC}"
./vendor/bin/pint --test

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}3.... php code fixer${NC}"
    exit 1
fi

if [ "$laravelVersion" == v8* ]; then
    # ----------------------------------------------------------------------------------------
    # 4. Larastan
    echo "${BBlue}4. Larastan${NC}"
    ./vendor/bin/phpstan analyse

    STATUS_CODE=$?
    if [ $STATUS_CODE -ne 0 ]; then
        echo "${BRed}4.... larastan${NC}"
        exit 1
    fi

    # ----------------------------------------------------------------------------------------
    # 5. PHP Unit Tests
    echo "${BBlue}5. Running Tests${NC}"
    php artisan test --parallel

    STATUS_CODE=$?
    if [ $STATUS_CODE -ne 0 ]; then
        echo "${BRed}5.... phpunit tests${NC}"
        exit 1
    fi
else
    # ----------------------------------------------------------------------------------------
    # 4. PHP Unit Tests
    echo "${BBlue}4. Running Tests${NC}"
    php artisan test --parallel

    STATUS_CODE=$?
    if [ $STATUS_CODE -ne 0 ]; then
        echo "${BRed}4.... phpunit tests${NC}"
        exit 1
    fi
fi
