#!/bin/sh

echo "1. Install .git/hooks/pre-rebase"
curl https://raw.githubusercontent.com/iammayron/devsquad-setup/master/hooks/pre-rebase -Ls > .git/hooks/pre-rebase

echo "2. Install .git/hooks/pre-push"
curl https://raw.githubusercontent.com/iammayron/devsquad-setup/master/hooks/pre-push -Ls > .git/hooks/pre-push

echo "3. Install .git/hooks/commit-msg"
curl https://raw.githubusercontent.com/iammayron/devsquad-setup/master/hooks/commit-msg -Ls > .git/hooks/commit-msg
