#!/bin/sh

echo "1. Install .git/hooks/pre-rebase"
curl -o .git/hooks/pre-rebase --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/hooks/pre-rebase
chmod +x .git/hooks/pre-rebase

echo "2. Install .git/hooks/pre-push"
curl -o .git/hooks/pre-push --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/hooks/pre-push
chmod +x .git/hooks/pre-push

echo "3. Install .git/hooks/commit-msg"
curl -o .git/hooks/commit-msg --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/hooks/commit-msg
chmod +x .git/hooks/commit-msg
