#!/bin/sh

npm install husky --save-dev
npx husky install
npm pkg set scripts.prepare "husky install"

# yarn only
npm pkg set scripts.postinstall "husky install"

echo "1. Install .git/hooks/pre-rebase"
curl -s -o .git/hooks/pre-rebase "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/hooks/pre-rebase"
chmod +x .git/hooks/pre-rebase

echo "2. Install .git/hooks/pre-push"
curl -s -o .git/hooks/pre-push "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/hooks/pre-push-sail"
chmod +x .git/hooks/pre-push

echo "3. Install .git/hooks/commit-msg"
curl -s -o .git/hooks/commit-msg "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/hooks/commit-msg"
chmod +x .git/hooks/commit-msg
