name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      DB_DATABASE: testing

    steps:
      - uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Node Modules
        run: npm ci

      - name: Build Assets
        run: npm run prod

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: PHP Mess Detector
        run: ./vendor/bin/phpmd app text ./phpmd.xml

      - name: PHP Code Sniffer
        run: ./vendor/bin/phpcs --standard=phpcs.xml

      - name: Check route integrity
        run: php artisan route:list -c

      - name: PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --verbose --stop-on-violation

      - name: Run Migrations
        run: php artisan migrate --force
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --parallel --configuration phpunit-ci.xml
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Run seeds
        run: php artisan db:seed
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Run Migrations Rollback
        run: php artisan migrate:rollback --force
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

  deploy:
    needs: testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli --update-with-dependencies

      - name: Deploy
        run: vapor deploy production
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
