#!/bin/sh

echo "1. Install .github/workflows/test.yml"
curl https://raw.githubusercontent.com/iammayron/devsquad-setup/master/actions/test.yml -Ls > .github/workflows/test.yml

echo "\n${BBlue}Is this project using Vapor? (Please enter: Y for yes or N for no)${NC}"
read VAPOR;

if [[ "$VAPOR" == "Y" ]]
then
  echo "\n${BBlue}Have this project a sandbox environment? (Please enter: Y for yes or N for no)${NC}"
  read SANDBOX;

  if [[ "$SANDBOX" == "Y" ]]
  then
    echo "2. Install .github/workflows/deploy-sandbox.yml"
    curl https://raw.githubusercontent.com/iammayron/devsquad-setup/master/actions/deploy-sandbox.yml -Ls > .github/workflows/deploy-sandbox.yml

    echo "\n${BBlue}Have this project a staging environment? (Please enter: Y for yes or N for no)${NC}"
    read STAGING;

    if [[ "$STAGING" == "Y" ]]
    then
      echo "3. Install .github/workflows/deploy-staging.yml"
      curl https://raw.githubusercontent.com/iammayron/devsquad-setup/master/actions/deploy-staging.yml -Ls > .github/workflows/deploy-staging.yml
    fi
  else
    echo "\n${BBlue}Have this project a staging environment? (Please enter: Y for yes or N for no)${NC}"
    read STAGING;

    if [[ "$STAGING" == "Y" ]]
    then
      echo "2. Install .github/workflows/deploy-staging.yml"
      curl https://raw.githubusercontent.com/iammayron/devsquad-setup/master/actions/deploy-staging-without-sandbox.yml -Ls > .github/workflows/deploy-staging.yml
    fi
  fi

  if [[ "$SANDBOX" == "Y" && "$STAGING" == "Y" ]]
  then
    echo "4. Install .github/workflows/deploy-production.yml"
  else
    echo "3. Install .github/workflows/deploy-production.yml"
  fi
  curl https://raw.githubusercontent.com/iammayron/devsquad-setup/master/actions/deploy-production.yml -Ls > .github/workflows/deploy-production.yml
fi
