#!/bin/sh

echo "\n${BRed}Is this project using Vapor? (Y for yes or N for no)${NC}"
read VAPOR

if [[ "$VAPOR" == "Y" ]]
then
  echo "\n${BRed}Have this project a sandbox environment? (Y for yes or N for no)${NC}"
  read SANDBOX

  echo "\n${BRed}Have this project a staging environment? (Y for yes or N for no)${NC}"
  read STAGING

  echo "\n1. Install .github/workflows/test.yml"
  curl -s -o .github/workflows/test.yml --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/actions/test.yml

  echo "2. Install .github/workflows/deployment-notifications.yml"
  curl -s -o .github/workflows/deployment-notifications.yml --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/actions/deployment-notifications.yml

  productionStep=3
  if [[ "$SANDBOX" == "Y" && "$STAGING" == "Y" ]]
  then
    echo "3. Install .github/workflows/deploy-sandbox.yml"
    curl -s -o .github/workflows/deploy-sandbox.yml --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/actions/deploy-sandbox.yml

    echo "4. Install .github/workflows/deploy-staging.yml"
    curl -s -o .github/workflows/deploy-staging.yml --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/actions/deploy-staging.yml

    productionStep=5
  else
    if [[ "$STAGING" == "Y" ]]
    then
      echo "3. Install .github/workflows/deploy-staging.yml"
      curl -s -o .github/workflows/deploy-staging.yml --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/actions/deploy-staging-without-sandbox.yml

      productionStep=4
    fi
  fi

  echo "${productionStep}. Install .github/workflows/deploy-production.yml"
  curl -s -o .github/workflows/deploy-production.yml --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/actions/deploy-production.yml
else
  echo "1. Install .github/workflows/test.yml"
  curl -s -o .github/workflows/test.yml --create-dirs https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/actions/test.yml
fi
